name: branch-aware ci/cd workflow
on:
    workflow_run: 
jobs:
    test:
        runs-on: ubuntu-slim
        steps:
            - run: echo "testing..."

    diagnostics:
        needs: test
        if: always()
        runs-on: ubuntu-slim
        steps:
            - run: |
                echo "${{github.ref}}"
                echo "${{github.sha}}"
                echo "${{github.actor}}"

    deploy:
        needs: test
        if: success() && github.ref == 'refs/heads/main'
        runs-on: ubuntu-slim
        steps:
            - run: |
                echo "deploying..."
                echo "${{github.sha}}"
