name: phase2-lab-3

on:
  workflow_run: 
jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - run: echo "lining..."
  test:
    runs-on: ubuntu-slim
    steps:
      - run: echo "testing..."
  security:
    runs-on: ubuntu-slim
    steps:
      - run: echo "security..."

  build:
    needs: [lint,test,security]
    runs-on: ubuntu-slim
    steps:
      - run: echo "building..."
