name: Variables and Secrets
run-name: variables and secrets example

on:
  push:
    branches: ['main']
  
env:
  APP_NAME: variable-demo
jobs:
  var-demo:
    environment: testing
    runs-on: ubuntu-slim

    steps:
      - run: |
          echo "APP_NAME       = ${{env.APP_NAME}}"
          echo "DEPLOY_REGION  = ${{vars.DEPLOY_REGION}}"
          echo "DEMO_TOKEN    = ${{secrets.DEMO_TOKEN}}"
    
