name: aws oidc connect
run-name: aws oidc connection expample


on:
  push:
    branches: ['main']

permissions: 
  id-token: write
  contents: read

jobs:
  connect:
    environment: testing
    runs-on: ubuntu-slim
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_USER}}:role/github-action-oidc 
          aws-region: us-east-1
          audience: sts.amazonaws.com
      - name: verify aws idendity
        run: |
         aws sts get-caller-identity
    
