name: phase3-lab-1
run-name: phase 3 lab 1
on:
  workflow_run: 

jobs:

  test:
    runs-on: ubuntu-slim
    if: always()
    steps:
      - run: |
          echo "Branch/Ref   : ${{github.ref}}"
          echo "Commit SHA   : ${{github.sha}}"
          echo "Actor        : ${{github.actor}}"
          
  deployment:
    needs: test
    runs-on: ubuntu-slim
    if: success() && github.ref == 'refs/heads/production'
    steps:
      - name: run
        run: echo "deployment running"
