name: aws oidc connect
run-name: aws oidc connection expample


on:
  push:
    branches: ['main']
  workflow_call: 

permissions: 
  id-token: write
  contents: read

jobs:
  connect-aws:
    environment: testing
    runs-on: ubuntu-slim
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6.3.0
      with:
        audience: sts.amazonaws.com
        role-to-assume: arn:aws:iam::${{secrets.AWS_USER}}:role/github-action-oidc 
        aws-region: us-east-1
       
    - name: verify aws idendity
      run: |
         aws sts get-caller-identity
    
