name: aws oidc connect
run-name: aws oidc connection expample


on:
  push:
    branches: ['main']

permissions: 
  id-token: write
  contents: read

jobs:
  connect:
    environment: testing
    runs-on: ubuntu-slim
    steps:
      - name: configure
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        
          audience: sts.amazonaws.com
      - name: verify aws idendity
        run: |
         aws sts get-caller-identity
    
