name: multi environment with permission

run-name: multi environment demo with permission


on:
  push:
    branches: ['main']
permissions:
  checks: write
  pull-requests: read

  
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - run: echo "build job"
    
  deploy-staging:
    needs: build
    environment: staging
    runs-on: ubuntu-slim
    steps:
      - run: |
          echo "STAGING_VAR = ${{vars.STAGING_VAR}}"
          echo "STAGING_SECRET = ${{secrets.STAGING_SECRET}}"
  
  deploy-production:
    needs: deploy-staging
    environment: production
    runs-on: ubuntu-slim
    steps:
      - run: |
          echo "PRODUCTION_VAR = ${{vars.PRODUCTION_VAR}}"
          echo "PRODUCTION_SECRET = ${{secrets.PRODUCTION_SECRET}}"
